import { Model, Agency, CastingCall, MusicPromotion } from './types';

export const POPULAR_TAGS = [
  'Runway 2026',
  'Haute Couture',
  'Commercial Acting',
  'Music Video Lead',
  'Editorial Vogue',
  'Paris Fashion Week',
  'Milan Representation',
  'SAG-AFTRA Feature',
  'Luxury Streetwear',
  'Beauty Campaign',
  'International Placement',
  'Direct Booking',
];

export const MODELS_DATA: Model[] = [
  {
    id: 1,
    name: 'Aria Montgomery',
    category: 'High Fashion',
    height: "5'11\" (180 cm)",
    bust: '32B',
    waist: '24"',
    hips: '34"',
    eyes: 'Hazel Green',
    hair: 'Dark Chestnut',
    shoes: '8.5 US / 39 EU',
    agency: 'Elite Paris & Milan',
    location: 'Paris, France',
    image: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=800&q=80',
    portfolioImages: [
      'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=1200&q=85',
      'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=1200&q=85',
      'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=1200&q=85',
      'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?auto=format&fit=crop&w=1200&q=85',
    ],
    bio: 'Opening model for Paris Fashion Week Fall/Winter. Featured on Italian Vogue and Yves Saint Laurent campaigns.',
    instagram: '@aria.montgomery',
    featured: true,
    tags: ['Runway', 'High Fashion', 'Vogue', 'Paris'],
    verified: true,
    experienceYears: 5,
  },
  {
    id: 2,
    name: 'Julian Vance',
    category: 'Editorial',
    height: "6'2\" (188 cm)",
    waist: '30"',
    hips: '37"',
    eyes: 'Ice Blue',
    hair: 'Platinum / Silver',
    shoes: '11 US / 44 EU',
    agency: 'DNA Model Management',
    location: 'New York, USA',
    image: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=800&q=80',
    portfolioImages: [
      'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=1200&q=85',
      'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=1200&q=85',
      'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&w=1200&q=85',
    ],
    bio: 'Contemporary editorial face known for sharp facial architecture and luxury fragrance campaigns (Armani, Dior).',
    instagram: '@julianvance.official',
    featured: true,
    tags: ['Editorial', 'Fragrance', 'New York', 'Dior'],
    verified: true,
    experienceYears: 4,
  },
  {
    id: 3,
    name: 'Elena Rostova',
    category: 'Runway',
    height: "5'10.5\" (179 cm)",
    bust: '33B',
    waist: '23.5"',
    hips: '34.5"',
    eyes: 'Deep Brown',
    hair: 'Espresso Black',
    shoes: '8 US / 38.5 EU',
    agency: 'Storm Management',
    location: 'London, UK',
    image: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=800&q=80',
    portfolioImages: [
      'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=1200&q=85',
      'https://images.unsplash.com/photo-1509967419530-da38b4704bc6?auto=format&fit=crop&w=1200&q=85',
      'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=1200&q=85',
    ],
    bio: 'Veteran of Chanel, Jacquemus, and Mugler runways. Fluid walker with extensive movement training.',
    instagram: '@elena_rostova',
    featured: true,
    tags: ['Runway', 'Chanel', 'Mugler', 'London'],
    verified: true,
    experienceYears: 6,
  },
  {
    id: 4,
    name: 'Marcus Kalu',
    category: 'Commercial',
    height: "6'1\" (185 cm)",
    waist: '31"',
    hips: '38"',
    eyes: 'Dark Amber',
    hair: 'Black / Taper Fade',
    shoes: '10.5 US / 44 EU',
    agency: 'IMG Models Worldwide',
    location: 'Los Angeles, USA',
    image: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=800&q=80',
    portfolioImages: [
      'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=1200&q=85',
      'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=1200&q=85',
    ],
    bio: 'Lead commercial talent for Apple, Nike, and GQ. Multi-disciplinary actor with music video lead credits.',
    instagram: '@marcus.kalu',
    featured: false,
    tags: ['Commercial', 'Nike', 'Los Angeles', 'Actor'],
    verified: true,
    experienceYears: 3,
  },
  {
    id: 5,
    name: 'Chloe Chevalier',
    category: 'Petite',
    height: "5'6\" (168 cm)",
    bust: '32C',
    waist: '24"',
    hips: '33"',
    eyes: 'Emerald',
    hair: 'Honey Blonde',
    shoes: '6.5 US / 37 EU',
    agency: 'Next Model Management',
    location: 'Monaco / Nice',
    image: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=800&q=80',
    portfolioImages: [
      'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=1200&q=85',
      'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=1200&q=85',
    ],
    bio: 'Specialist in luxury skincare, cosmetics, and jewelry close-up editorials for Cartier and Sephora.',
    instagram: '@chloechevalier',
    featured: false,
    tags: ['Beauty', 'Petite', 'Jewelry', 'Monaco'],
    verified: true,
    experienceYears: 4,
  },
  {
    id: 6,
    name: 'Kenji Takahashi',
    category: 'Fitness',
    height: "6'0\" (183 cm)",
    waist: '29"',
    hips: '36"',
    eyes: 'Dark Brown',
    hair: 'Jet Black',
    shoes: '10 US / 43 EU',
    agency: 'Bravo Models Tokyo',
    location: 'Tokyo, Japan',
    image: 'https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?auto=format&fit=crop&w=800&q=80',
    portfolioImages: [
      'https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?auto=format&fit=crop&w=1200&q=85',
      'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&w=1200&q=85',
    ],
    bio: 'Martial artist and high-performance athletic model for On Running, Under Armour, and Asics.',
    instagram: '@kenji.tkhsh',
    featured: true,
    tags: ['Fitness', 'Athletic', 'Tokyo', 'Performance'],
    verified: true,
    experienceYears: 5,
  },
];

export const MODELING_AGENCIES: Agency[] = [
  {
    id: 1,
    name: 'Elite World Model Management',
    type: 'modeling',
    location: 'Paris • New York • Milan',
    founded: 1972,
    rosterCount: 420,
    website: 'https://elitemodel.world',
    email: 'scouting@elitemodel.com',
    logo: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?auto=format&fit=crop&w=200&q=80',
    coverImage: 'https://images.unsplash.com/photo-1469334031218-e382a71b716b?auto=format&fit=crop&w=1200&q=80',
    description: 'Iconic global network representing supermodels and high-fashion runway icons across all four fashion capitals.',
    specialties: ['Haute Couture Runway', 'Editorial Campaigns', 'Global Scouting'],
    notableWork: ['Vogue Cover Series', 'Balenciaga S/S', 'Gucci Cruise'],
    openForSubmissions: true,
  },
  {
    id: 2,
    name: 'Storm Model Agency London',
    type: 'modeling',
    location: 'Chelsea, London, UK',
    founded: 1987,
    rosterCount: 280,
    website: 'https://stormmodels.com',
    email: 'newfaces@stormmanagement.com',
    logo: 'https://images.unsplash.com/photo-1513094735237-8f2714d57c13?auto=format&fit=crop&w=200&q=80',
    coverImage: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&w=1200&q=80',
    description: 'Boutique agency renowned for discovering generational British fashion icons with distinct artistic sensibilities.',
    specialties: ['Editorial Fashion', 'Commercial Beauty', 'Digital Influencers'],
    notableWork: ['Alexander McQueen', 'Burberry Heritage', 'Dazed Magazine'],
    openForSubmissions: true,
  },
  {
    id: 3,
    name: 'Bravo Talent Tokyo',
    type: 'modeling',
    location: 'Shibuya, Tokyo, Japan',
    founded: 1996,
    rosterCount: 190,
    website: 'https://bravomodels.tokyo',
    email: 'cast@bravomodels.co.jp',
    logo: 'https://images.unsplash.com/photo-1526772662000-3f88f10405ff?auto=format&fit=crop&w=200&q=80',
    coverImage: 'https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=1200&q=80',
    description: 'Asia-Pacific powerhouse bridging high-concept Japanese streetwear, tech campaigns, and international fashion weeks.',
    specialties: ['Streetwear Culture', 'Tech Commercials', 'APAC Direct Placement'],
    notableWork: ['Issey Miyake', 'Sacai', 'Sony Global Campaign'],
    openForSubmissions: true,
  },
];

export const MOVIE_AGENCIES: Agency[] = [
  {
    id: 101,
    name: 'Apex Cinema Talents Group',
    type: 'movie',
    location: 'Beverly Hills, CA, USA',
    founded: 1989,
    rosterCount: 150,
    website: 'https://apexcinemagroup.com',
    email: 'theatrical@apexcinemagroup.com',
    logo: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=200&q=80',
    coverImage: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=1200&q=80',
    description: 'Premier theatrical representation for Academy Award-winning actors, cinematic visionaries, and breakthrough character leads.',
    specialties: ['Theatrical Feature Leads', 'Prestige TV (HBO/Netflix)', 'Directorial Packaging'],
    notableWork: ['Cannes Film Festival Winners', 'A24 Features', 'Warner Bros Epics'],
    openForSubmissions: true,
  },
  {
    id: 102,
    name: 'Lumière Theatrical Paris',
    type: 'movie',
    location: '7th Arrondissement, Paris, France',
    founded: 1994,
    rosterCount: 95,
    website: 'https://lumiereparis.fr',
    email: 'casting@lumiereparis.fr',
    logo: 'https://images.unsplash.com/photo-1478720568477-152d9b164e26?auto=format&fit=crop&w=200&q=80',
    coverImage: 'https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?auto=format&fit=crop&w=1200&q=80',
    description: 'European cinema agency representing bilingual actors for French art-house, European co-productions, and international streaming series.',
    specialties: ['European Cinema', 'Bilingual Theatrical', 'Voice & ADR Localization'],
    notableWork: ['César Award Recipients', 'Venice Film Festival Selection', 'Canal+ Series'],
    openForSubmissions: false,
  },
];

export const CASTING_CALLS: CastingCall[] = [
  {
    id: 201,
    title: 'Neon Odyssey: Sci-Fi Feature',
    production: 'Aetheria Pictures (A24 Distributed)',
    role: 'Commander Vesper (Lead Protagonist)',
    type: 'Feature Film',
    location: 'London & Iceland',
    compensation: '$4,500/week + Points (SAG-AFTRA)',
    dates: 'Shooting Oct 12 – Dec 20, 2026',
    description: 'Seeking a commanding, emotionally versatile actor with athletic background for high-concept sci-fi feature.',
    requirements: [
      'Age range 24–36, any ethnicity',
      'Strong physical endurance / wirework readiness',
      'Accents: British RP or Standard American',
    ],
    deadline: 'Sept 15, 2026',
    image: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=800&q=80',
    urgent: true,
    director: 'Denis Villeneuve protege unit',
    unionStatus: 'SAG-AFTRA',
  },
  {
    id: 202,
    title: 'Maison Noir: Autumn Runway Campaign',
    production: 'Maison Noir Paris Fashion House',
    role: 'Principal Runway & Campaign Face',
    type: 'Runway',
    location: 'Paris, Grand Palais Éphémère',
    compensation: '€8,000 Flat + Worldwide Buyout',
    dates: 'Fittings Sept 28, Show Oct 02, 2026',
    description: 'Iconic fall luxury collection presentation with dynamic fluid staging and synchronized spatial audio.',
    requirements: [
      'Height: 5\'10"+ (Female) / 6\'1"+ (Male)',
      'Proven high-fashion runway experience',
      'Available for full day fitting & rehearsal',
    ],
    deadline: 'Sept 20, 2026',
    image: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&w=800&q=80',
    urgent: false,
    director: 'Jean-Luc Moreau',
    unionStatus: 'All Welcome',
  },
  {
    id: 203,
    title: 'Silicon Whisper: Commercial Tech Hero',
    production: 'Nordic Apple Agency Unit',
    role: 'Innovator / Key Lifestyle Face',
    type: 'Commercial',
    location: 'Copenhagen & Stockholm',
    compensation: '$12,000 Total Buyout (2-year TV/Digital)',
    dates: 'Shoot Nov 04 – Nov 07, 2026',
    description: 'Clean, minimalist high-aesthetic global tech launch commercial focusing on seamless human-device interaction.',
    requirements: [
      'Expressive natural micro-expressions',
      'Comfortable with hand modeling close-ups',
      'Passport valid for EU travel',
    ],
    deadline: 'Oct 01, 2026',
    image: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=800&q=80',
    urgent: true,
    director: 'Lars Lindqvist',
    unionStatus: 'Non-Union',
  },
];

export const MUSIC_PROMOTIONS: MusicPromotion[] = [
  {
    id: 301,
    artist: 'Luna Solaris',
    songTitle: 'Midnight In Velvet',
    genre: 'Synth-Pop / Darkwave',
    label: 'Astral Wave Records',
    releaseDate: 'October 2026',
    coverImage: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=800&q=80',
    description: 'A visual poem shot on 35mm anamorphic lenses in vintage Tokyo clubs and neon-drenched highway tunnels.',
    seekingRoles: ['Mystery Driver (Lead)', 'Choreographed Trio Dancers', 'Vogue Stylists'],
    budget: '$45,000 Production Tier',
    director: 'Kaito Moriyama',
    shootLocation: 'Tokyo & Yokohama',
    shootDate: 'Sept 25 – 28, 2026',
    moodboardImages: [
      'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=600&q=80',
      'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?auto=format&fit=crop&w=600&q=80',
    ],
  },
  {
    id: 302,
    artist: 'The Obsidian Echo',
    songTitle: 'Echoes of Chrome',
    genre: 'Alternative / Cinematic Rock',
    label: 'Subterranean Sound Group',
    releaseDate: 'November 2026',
    coverImage: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&w=800&q=80',
    description: 'High-concept black-and-white visual set in brutalist concrete architecture with dynamic light strobes.',
    seekingRoles: ['Sculptural High Fashion Model', 'Stunt Movement Artist'],
    budget: '$30,000 Production Tier',
    director: 'Hélène Vautier',
    shootLocation: 'Berlin, Kraftwerk',
    shootDate: 'Oct 14 – 16, 2026',
    moodboardImages: [
      'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&w=600&q=80',
      'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=600&q=80',
    ],
  },
];
